name: SonarCloud Analysis
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      # Set up .NET SDK
      - name: Setup_.NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0' 

      - name: Install_workloads
        run: dotnet workload install maui
        
      - name: Restore_dependencies
        run: dotnet restore VocalLink_L00152171.sln
        
      - name: Build
        run: dotnet build VocalLink_L00152171.sln 

      # Run analysis
      - name: SonarCloud_Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: "teganmcdaid_VocalLink_L00152171"
          organization: "teganmcdaid"

