name: SonarCloud Analysis
#run on push to master
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Set up .NET (if needed)
      - name: Setup_dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install_workloads
        run: dotnet workload install maui 

      - name: Restore_dependencies
        run: dotnet restore VocalLink_L00152171.sln

      - name: Build
        run: dotnet build VocalLink_L00152171.sln

      #Run SonarCloud analysis
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: teganmcdaid
          projectKey: VocalLink_L00152171
          token: ${{ secrets.SONAR_TOKEN }}
