name: SonarCloud Analysis
#run on push to master
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: write
  
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup_dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install_workloads
        run: dotnet workload install maui 

      - name: Install_SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      #need to add tool to path so recognised
      - name: Add_scanner_to_PATH
        run: echo "${{ env.USERPROFILE }}\.dotnet\tools" >> $GITHUB_PATH

      - name: Restore_dependencies
        run: dotnet restore VocalLink_L00152171.sln

      #run analysis
      - name: Start_SonarCloud
        run: dotnet sonarscanner begin /k:"VocalLink_L00152171" /o:"teganmcdaid" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.projectBaseDir="$(github.workspace)"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: dotnet build VocalLink_L00152171.sln

      - name: End_SonarCloud
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
