on:
#trigger when pushing to master and doing a pull request
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    
name: Main Workflow
permissions:
  contents: read
jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      #install sdk for bulding
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      #build project before analysis
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: teganmcdaid
          projectKey: VocalLink_L00152171
          token: ${{ secrets.SONAR_TOKEN }}
